apiVersion: v1
kind: Service
metadata:
  name: dental-chart-backend
  namespace: dental-chart
  labels:
    app.kubernetes.io/name: dental-chart
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dental-chart
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 3001
