/**
 * AI Service handles communication with Modal AI endpoints 
 * and local inference result management.
 */
export const aiService = {
    /**
     * Loads the static detections.json file generated by the Modal pipeline.
     */
    getDetections: async () => {
        try {
            const response = await fetch('/detections.json');
            if (!response.ok) throw new Error('Detections file not found');
            return await response.json();
        } catch (error) {
            console.error('[AI Service] Failed to fetch detections', error);
            throw error;
        }
    }
};
